[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # If you add Netlify functions, set the folder here
  # directory = "netlify/functions"

[context.production.environment]
# Set any environment variables required in Netlify UI (or leave empty)
# VITE_BASE_PATH = "/my-base/"
